[project]
name = "eventide-h9-control"
version = "0.1.0"
description = "A Qt UI for the Eventide H9 effects unit."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mido>=1.3.3",
    "pyside6>=6.10.1",
    "python-rtmidi>=1.5.8",
]
